BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[mataKuliah] (
    [id] NVARCHAR(1000) NOT NULL,
    [mataKuliah] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [mataKuliah_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [mataKuliah_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
